name: Github Actions Test

on: push

jobs:
  test1:
    env:
      result_file: result.log
    runs-on: ubuntu-latest
    steps:

    - name: Send time start jobs
      id: time
      run: |
        echo "Start timer:  $(date '+%F %T')" >> ${{ env.result_file }}
        echo "start_timer=$(date '+%s')" >> $GITHUB_OUTPUT

    - name: Waiter
      run: sleep 3

    - name: Send time finish jobs
      run: |
        echo "Stop timer: $(date '+%F %T')" >> ${{ env.result_file }}
        echo "Time spended: $(($(date '+%s')-${{ steps.time.outputs.start_timer }})) seconds" >> ${{env.result_file}}



#    - name: Send time start jobs
#      run: |
#        echo "Start deployment:  $(date '+%F %T')" >> ${{ env.result_file }}
#
#    - name: Waiter
#      run: sleep 3
#
#    - name: Send time finish jobs
#      run: |
#        echo "Finish deployment: $(date '+%F %T')" >> ${{ env.result_file }}

#    - name: Simple timer inside Action
#      run: |
#        SECONDS=0
#        sleep 3
#        echo "Elapsed Time: $SECONDS seconds" >> ${{ env.result_file }}

    - name: Additional information in log file
      run: |
        sed -i '1 i\Repository: ${{ github.repository }}' ${{ env.result_file }}
        sed -i '2 i\Workflow: ${{ github.workflow }}' ${{ env.result_file }}

    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      with:
        channel-id: 'C04EWNX7BT3'
        payload: |
          {
            "text": "TEXT in there",
            "attachments": [
              {
                "pretext": "",
                "color": "ff0000",
                "fields": [
                  {
                    "title": "this is TITLE",
                    "short": true,
                    "value": "This is value\nSee the ${{ env.result_file }} for details."
                  }
                ]
              }
            ]
          }


    - name: Upload to slack step
      uses: adrey/slack-file-upload-action@master
      with:
        token: ${{ secrets.SLACK_TOKEN }}
        path: ${{ env.result_file }}
        channel: github_action

#    - name: Send telegram message on push
#      uses: appleboy/telegram-action@master
#      with:
#        to: ${{ secrets.TELEGRAM_TO }}
#        token: ${{ secrets.TELEGRAM_TOKEN }}
#        message: |
#          ${{ github.actor }} created commit:
#          Commit message: ${{ github.event.commits[0].message }}
#          Repository: ${{ github.repository }}
#          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
#        document: ${{ env.result_file}}
