name: Github Actions Test

on: push

jobs:
  simple_timer:
    env:
      result_file: result.log
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:

    - name: Send time start jobs
      id: time
      run: |
        echo "Start timer:  $(date '+%F %T')" >> ${{ env.result_file }}
        echo "start_timer=$(date '+%s')" >> $GITHUB_OUTPUT

    - name: Waiter
      run: sleep 3

    - name: Send time finish jobs
      run: |
        echo "Stop timer: $(date '+%F %T')" >> ${{ env.result_file }}
        echo "Time spended: $(($(date '+%s')-${{ steps.time.outputs.start_timer }})) seconds" >> ${{env.result_file}}

    - name: Additional information in log file
      run: |
        sed -i '1 i\Repository: ${{ github.repository }}' ${{ env.result_file }}
        sed -i '2 i\Workflow: ${{ github.workflow }}' ${{ env.result_file }}

    - name: Send to Slack
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      with:
        channel-id: 'C04EWNX7BT3'
        payload: |
          {
            "text": "Gihtub Action report",
            "attachments": [
              {
                "pretext": "",
                "color": "00aa00",
                "fields": [
                  {
                    "title": "this is TITLE",
                    "short": true,
                    "value": "This is value\nSee the ${{ env.result_file }} for details."
                  }
                ]
              }
            ]
          }


    - name: Upload to slack step
      uses: adrey/slack-file-upload-action@master
      with:
        token: ${{ secrets.SLACK_TOKEN }}
        path: ${{ env.result_file }}
        channel: github_action
